###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://localhost/instructionmanagement
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
