###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://localhost/tutorialmanagement
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
